### ISSUE TITLE
map not completely loading

### ISSUE THREAD

**Issue by AkihitoNarihisago** [Turun/GrepolisMap#2]
checking "all tows" - should reveal all towns 

server: ro109 - Leontini
version 1.3.4, 1.3.5

![Image](https://github.com/user-attachments/assets/f1025451-3b96-4031-a6ac-d808e10107b0)

**Comment by AkihitoNarihisago** [comment]
not really familiar with rust, i will make some time to read the code, just making some notes.

**Comment by Turun** [comment]
These are all the towns on the server. (as per the latest API state when you clicked "load data from server")

You maybe want all island locations shown as well? That is indeed not implemented yet. I did not do that, because for the most part you can't interact with those spots anyway and the API does not tell me if spots are open/interactable or not.

If you really want to add that you'd have to add two new MessageTypes (`src/message.rs`, one for requesting the data from the backend, one for sending the data to the frontend), emit it to the backend on server data reload (`src/view/mod.rs:310`), add the corresponding handler code for the backend (`src/presenter.rs`, calling `src/model/mod.rs`, calling `src/model/database.rs` (it's probably easiest to write the SQL inline here)), the button on the frontend (`src/view/sidepanel.rs:26`) and draw the positions in the map (`src/view/map.rs:117`). The Data struct (`src/view/data.rs`) needs to be expanded as well to hold the data for the frontend (add a field for the island locations like there are the `all_towns` and `ghost_towns` fields).

---

In the mean time: Here's a hack to highlight all towns on islands that are not yet fully colonized, which usually (but not always!)indicates that the remaining town spots are usable:

```yaml
- name: Siedlungsinseln
  constraints:
  - IslandTowns GreaterThan '1'
  - IslandType InSelection Inseln gesamt
  constraint_join_mode: And
  color:
  - 43
  - 45
  - 0
  - 7
- name: Inseln gesamt
  constraints:
  - IslandType InSelection Inseln1
  - IslandType InSelection Inseln2
  constraint_join_mode: Or
  color:
  - 0
  - 0
  - 0
  - 0
- name: Inseln1
  constraints:
  - IslandType GreaterThan '1'
  - IslandType LessThan '10'
  constraint_join_mode: And
  color:
  - 0
  - 0
  - 0
  - 0
- name: Inseln2
  constraints:
  - IslandType GreaterThan '37'
  - IslandType LessThan '46'
  constraint_join_mode: And
  color:
  - 0
  - 0
  - 0
  - 0
```
(any yes, I do regret choosing YAML for that selection export XD)
